function bmoempower(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',gc='.cache.html',_='/',lb='//',Wb='0C68653554DCD7D70F82C099B64E19F2',Yb='2687281554726D61540624FB701717BF',Zb='5E94DB534B63313C165B5F1F58095ADF',$b='678CB7706837B0F9148E0D5AC15F0DCF',_b='81FF222D2F452BC470F4C57DB1E0DB4C',fc=':',Xb=':1',pb='::',pc='<script defer="defer">bmoempower.onInjectionDone(\'bmoempower\')<\/script>',hb='<script id="',sb='=',$='?',ac='ABD60E25DC21F40FA3928143AAEDF01A',ub='Bad handler "',bc='CE2504F99D810EA33AB077C02E007914',cc='D87755BE29C383239B1EC027020617BD',dc='DF720E878B67CC52C085DA0F35C9E555',oc='DOMContentLoaded',ec='F16F19F527D98738F4067F6BD0359274',jb='SCRIPT',gb='__gwt_marker_bmoempower',kb='base',cb='baseUrl',T='begin',Q='bmoempower',eb='bmoempower.nocache.js',ob='bmoempower::',S='bootstrap',bb='clear.cache.gif',rb='content',hc='core/standard/minimal.css',Y='end',Fb='file',Cb='fileapi.support',Qb='gecko',Rb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',mc='head',Ub='hosted.html?bmoempower',lc='href',Pb='ie6',Ob='ie8',Nb='ie9',yb='iframe',ab='img',Db='input',zb="javascript:''",ic='link',Tb='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Mb='msie',nb='name',Gb='no',Jb='opera',Ab='position:absolute;width:0;height:0;border:none',jc='rel',Lb='safari',db='script',Vb='selectingPermutation',R='startup',kc='stylesheet',Eb='type',fb='undefined',Sb='unknown',Ib='user.agent',Kb='webkit',nc='xmlarchiving.css',Hb='yes';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}bmoempower=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=document.createElement(Db);a.setAttribute(Eb,Fb);return a.files==null?Gb:Hb};v[Cb]={no:0,yes:1};w[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&n.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&n.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};v[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};bmoempower.onScriptLoad=function(){if(I){r=true;C()}};bmoempower.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Ub;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Vb});if(!B()){try{G([Gb,Pb],Wb);G([Hb,Pb],Wb);G([Gb,Pb],Wb+Xb);G([Hb,Pb],Wb+Xb);G([Gb,Lb],Yb);G([Hb,Nb],Zb);G([Hb,Rb],$b);G([Gb,Rb],_b);G([Gb,Jb],ac);G([Hb,Jb],bc);G([Gb,Nb],cc);G([Hb,Lb],dc);G([Gb,Ob],ec);G([Hb,Ob],ec);G([Gb,Ob],ec+Xb);G([Hb,Ob],ec+Xb);K=x[H(Cb)][H(Ib)];var M=K.indexOf(fc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+gc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[hc]){var a=n.createElement(ic);__gwt_stylesLoaded[hc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+hc);n.getElementsByTagName(mc)[0].appendChild(a)}if(!__gwt_stylesLoaded[nc]){var a=n.createElement(ic);__gwt_stylesLoaded[nc]=a;a.setAttribute(jc,kc);a.setAttribute(lc,t+nc);n.getElementsByTagName(mc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(oc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(oc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:T});n.write(pc)}
bmoempower();